name: Test
on:
  push:
  branches: [ "main" ]

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    steps: 
    - name: Git Clone
      uses: actions/checkout@v4
    - name: init
      run: terraform init